### ISSUE TITLE
Maximum Limits of the video Triming...

### ISSUE THREAD

**Issue by iHarshDarji** [pikachu987/VideoTrim#1]
Hey, You are really awesome..i m using using your library in my project . but i am  stuck at one point.. my requirement is user must trim video maximum 40 seconds ..less than 40 secondswhat ever he want...i have upper bound but dont have lower bound... means maximum limit i have is 40 seconds ..i dont have any lower limits.can you give me solution ?
Thnx in Advance. @pikachu987

**Comment by pikachu987** [comment]
Thank you for using the library.
In 0.1.2 version, trimMaximumDuration Property was added.
🖐
